### ISSUE TITLE
Change the api endpoint

### ISSUE THREAD

**Issue by Pavanct** [Pavanct/mensawebapp#19]
please change the mensa-api base url endpoint to - https://mensa-api.pavanct.com

**Comment by Pavanct** [comment]
okay ignore it, i see its connecting to openmensa endpoint

**Comment by meghabalaraju** [comment]
The API endpoint that you mentioned here https://mensa-api.pavanct.com/ just shows "Hello world!" Is there any other endpoint that you have created like

https://mensa-api.pavanct.com/ canteens/
https://mensa-api.pavanct.com/ dishes/

Or should I continue working on the same endpoint?


________________________________
